[workspace]
members = ["cargo:activitywatch-ls"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.27.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
unix-archive = ".zip"
windows-archive = ".zip"

[env]
OPENSSL_STATIC = 1
OPENSSL_LIB_DIR = "/usr/lib/x86_64-linux-gnu"
OPENSSL_INCLUDE_DIR = "/usr/include/openssl"
#[workspace.metadata.dist.dependencies.apt]
#gcc-aarch64-linux-gnu = { version = '*', targets = [
#  "aarch64-unknown-linux-gnu",
#  "aarch64-unknown-linux-musl",
#] }
#
#[env]
#CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"
#
#[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-linux-gnu-gcc"
#
#[target.aarch64-unknown-linux-musl]
#linker = "aarch64-linux-gnu-gcc"
